controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute



app_candidat:
  path: /candidat
  controller: App\Controller\CandidatController::index
